
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'"h8j\xfbF O\xf8\x05\x10\xef\x0b\xc7_\x98'
    
_lr_action_items = {'PRONOUN':([0,],[1,]),'QUANTITY':([5,],[8,]),'NOUN':([2,7,8,],[6,9,-4,]),'ADJECTIVE':([2,8,],[7,-4,]),'$end':([3,4,6,9,],[-1,0,-3,-2,]),'VERB':([1,],[5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'SEN':([0,],[3,]),'PVQ':([0,],[2,]),'START':([0,],[4,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> START","S'",1,None,None,None),
  ('START -> SEN','START',1,'p_START','C:/PyWorkspace/ToolChainDemo/PLYDemo.py',44),
  ('SEN -> PVQ ADJECTIVE NOUN','SEN',3,'p_SEN','C:/PyWorkspace/ToolChainDemo/PLYDemo.py',49),
  ('SEN -> PVQ NOUN','SEN',2,'p_SEN','C:/PyWorkspace/ToolChainDemo/PLYDemo.py',50),
  ('PVQ -> PRONOUN VERB QUANTITY','PVQ',3,'p_PVQ','C:/PyWorkspace/ToolChainDemo/PLYDemo.py',55),
]
